version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/app
    networks: 
      - nginx_network
      - db_network
    depends_on:
      - db

  db:
    image: mysql
    volumes: 
      - ./db/:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
       MYSQL_HOST: localhost
       MYSQL_PORT: 3306
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - db_network

  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./home/static:/opt/services/djangoapp/src/home/static
    depends_on:
      - djangoapp
    networks: 
      - nginx_network

networks:  
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

